#!/usr/bin/env python3
"""Generate an ngspice deck from the SAME netlist the PCB is built from.

The point is that the simulation cannot drift from the thing that gets
manufactured.  Every other checker in this project re-derives what it
checks rather than trusting an upstream copy; a hand-typed SPICE netlist
would be exactly the "hand-maintained second copy" that this repo has
been bitten by twice already (the parts table, the footprint geometry).
So the devices come out of docs/netlist-*.json, and the only thing
written by hand here is the physics: what an MC33079 section, a J111 and
a 1N4148 actually do.

Writes:
    sim/crossover.net   devices, from the netlist JSON
    sim/models.lib      device models, hand-written and commented

Both are inputs to the analysis decks in sim/.

Knobs, all exposed as .param so an analysis can sweep them:
    kf      frequency-pot rotation, 0..1   (VR1, VR2 - ganged in the real part)
    kv      band volume-pot rotation, 0..1 (VR3, VR4, VR5)
    km      master volume rotation, 0..1   (VR6)
    mute1/2/3   1 = that band's button pressed (muted), 0 = released
    rload   amplifier input impedance hung on each output
"""

import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SLUG = "esp-p148-3way-crossover-retuned-quad-smd"
NET = os.path.join(ROOT, "docs", "netlist-%s.json" % SLUG)
OUT = os.path.join(ROOT, "sim")

# MC33079 / any 14-pin quad: which package pin is which section terminal.
# Read straight off the netlist to confirm - U1A ties pins 1 and 2 together
# and takes its signal on 3, which is a unity-gain buffer and is exactly
# what the input buffer should be.
QUAD_PINS = {"A": ("3", "2", "1"), "B": ("5", "6", "7"),
             "C": ("10", "9", "8"), "D": ("12", "13", "14")}
VPLUS_PIN, VMINUS_PIN = "4", "11"

# A DPDT with commons on 4 and 3, throws (1,2) and (5,6) - see
# gen_schematic.switch_dpdt().  Pressed connects 4-1 and 3-2; released
# connects 4-5 and 3-6.
SW_PRESSED = [("4", "1"), ("3", "2")]
SW_RELEASED = [("4", "5"), ("3", "6")]


def spice_net(n):
    """Net name ngspice will accept.  GND is node 0; the rails get names
    that do not start with a sign."""
    if n == "GND":
        return "0"
    if n == "+15V":
        return "VCC"
    if n == "-15V":
        return "VEE"
    return re.sub(r"[^A-Za-z0-9_]", "_", n)


def value(v):
    """'5.6k' -> '5.6k', '100R' -> '100', '33nF' -> '33n', '1M' -> '1meg'.

    SPICE reads M as milli, so a 1M resistor written '1M' becomes one
    milliohm - which would put the JFET gate resistors a billion times too
    low and silently break the whole mute analysis.  This is the one unit
    trap in the file and it is worth the explicit test below."""
    v = v.strip()
    m = re.match(r"^([\d.]+)\s*([A-Za-zΩ]*)$", v)
    if not m:
        return v
    num, suf = m.group(1), m.group(2)
    suf = {"R": "", "k": "k", "K": "k", "M": "meg", "nF": "n", "uF": "u",
           "pF": "p", "n": "n", "u": "u", "p": "p", "": ""}.get(suf, suf)
    return num + suf


def load():
    doc = json.load(open(NET))
    pins = {}
    for name, members in doc["nets"].items():
        for m in members:
            ref, _, pin = m.rpartition(".")
            pins.setdefault(ref, {})[pin] = name
    return doc, pins


def emit(doc, pins):
    parts = doc["parts"]
    L = []
    A = L.append
    A("* %s - generated by tools/gen_spice.py, do not edit" % SLUG)
    A("* Devices come from docs/netlist-%s.json; models are in models.lib" % SLUG)
    A("")
    A(".param kf1=0.5 kf2=0.5 kv=1.0 km=1.0")
    A(".param mute1=0 mute2=0 mute3=0")
    A(".param rload=10k")
    A("")
    A("* ---- supplies (J1) ----")
    A("* DC for .op and .ac; the PWL ramp is what .tran sees, so a")
    A("* transient starts from genuinely dead rails and the soft-start")
    A("* circuit is exercised rather than assumed.")
    A("* tramp: how long the rails take to come up.")
    A("* tfall/tcollapse: when, and how fast, they die - default far enough")
    A("* into the future that an ordinary transient never reaches it.")
    A(".param tramp=10m tfall=1000 tcollapse=50m")
    A("VCC VCC 0 DC 15  PWL(0 0 {tramp} 15 {tfall} 15 {tfall+tcollapse} 0)")
    A("VEE VEE 0 DC -15 PWL(0 0 {tramp} -15 {tfall} -15 {tfall+tcollapse} 0)")
    A("")

    def n(ref, pin):
        return spice_net(pins[ref][pin])

    # ---- passives ------------------------------------------------------
    A("* ---- resistors ----")
    for ref in sorted(pins):
        if ref.startswith("R"):
            A("R%s %s %s %s" % (ref[1:], n(ref, "1"), n(ref, "2"),
                                value(parts[ref]["value"])))
    A("")
    A("* ---- capacitors ----")
    for ref in sorted(pins):
        if ref.startswith("C"):
            A("C%s %s %s %s" % (ref[1:], n(ref, "1"), n(ref, "2"),
                                value(parts[ref]["value"])))
    A("")

    # ---- potentiometers -------------------------------------------------
    # pin 1 = one end, pin 2 = wiper, pin 3 = other end.  A pot with its
    # wiper strapped to an end (VR1/VR2 here) is a rheostat, and emitting
    # the second element would be a resistor from a node to itself.
    A("* ---- potentiometers (k = rotation, 0..1) ----")
    for ref in sorted(pins):
        if not ref.startswith("VR"):
            continue
        # The gangs carry the value, not the package: parts has VR1A and
        # VR1B, not VR1.  Looking up the base name first silently gave
        # every frequency pot 10k instead of 20k, which would have moved
        # the whole tuning range and looked like a design error.
        _v = (parts.get(ref) or parts.get(re.sub(r"[AB]$", "", ref))
              or {}).get("value")
        if _v is None:
            raise SystemExit("no value for pot %s" % ref)
        total = value(re.match(r"([\d.]+[kM]?)", _v).group(1))
        # VR1 and VR2 get their OWN parameter.  They are separate knobs on
        # the panel, so ganging them in the model would hide the case that
        # matters most: the user winding the two crossover points until
        # they nearly coincide, which is reachable and is where a 3-way
        # summed response is worst.
        k = {"VR1": "kf1", "VR2": "kf2", "VR6": "km"}.get(
            re.sub(r"[AB]$", "", ref), "kv")
        top, wip, bot = n(ref, "1"), n(ref, "2"), n(ref, "3")
        # A tiny floor stops a rotation of exactly 0 or 1 creating a
        # zero-ohm branch, which is a voltage source in disguise.
        A("R%s_a %s %s {max(1-%s,1e-4)*%s}" % (ref, top, wip, k, total))
        if bot != wip:
            A("R%s_b %s %s {max(%s,1e-4)*%s}" % (ref, wip, bot, k, total))
    A("")

    # ---- op-amp sections ------------------------------------------------
    A("* ---- op-amp sections (MC33079 quad) ----")
    for ref in sorted(pins):
        m = re.match(r"^(U\d+)([A-D])$", ref)
        if not m:
            continue
        pkg, sec = m.groups()
        p, i, o = QUAD_PINS[sec]
        # The supply pins are declared on one section of each package only,
        # which is the usual convention - so look them up package-wide.
        A("X%s %s %s %s VCC VEE OPAMP" % (ref, n(ref, p), n(ref, i), n(ref, o)))
    A("")

    # ---- JFET mute shunts ----------------------------------------------
    A("* ---- mute shunt JFETs (pin 1 drain, 2 source, 3 gate) ----")
    for ref in sorted(pins):
        if ref.startswith("Q"):
            A("J%s %s %s %s JFET" % (ref[1:], n(ref, "1"), n(ref, "3"),
                                     n(ref, "2")))
    A("")
    A("* ---- diodes ----")
    for ref in sorted(pins):
        if ref.startswith("D"):
            A("D%s %s %s D1N4148" % (ref[1:], n(ref, "1"), n(ref, "2")))
    A("")

    # ---- the mute buttons ----------------------------------------------
    # Modelled as resistors whose value the mute<N> parameter switches
    # between a short and an open.  A real latching contact is either one
    # or the other and nothing in between, so this needs no switch model.
    A("* ---- mute buttons (DPDT latching; mute<N>=1 means pressed) ----")
    for idx, ref in enumerate(sorted(r for r in pins if r.startswith("SW")), 1):
        num = ref[2:]
        par = "mute%s" % num
        for tag, (ca, cb) in zip("ab", SW_PRESSED):
            A("R%s_p%s %s %s {%s>0.5 ? 1m : 1G}"
              % (ref, tag, n(ref, ca), n(ref, cb), par))
        for tag, (ca, cb) in zip("ab", SW_RELEASED):
            A("R%s_r%s %s %s {%s>0.5 ? 1G : 1m}"
              % (ref, tag, n(ref, ca), n(ref, cb), par))
    A("")

    # ---- panel hardware on J6 ------------------------------------------
    A("* ---- panel LEDs, off-board on the J6 loom ----")
    for led in ("LD1", "LD2", "LD3"):
        if any(led == v for d in pins.values() for v in d.values()):
            A("D%s %s 0 DLED" % (led, spice_net(led)))
    A("")

    # ---- ports ----------------------------------------------------------
    A("* ---- input (J2) and the amplifier loads on J3/J4/J5 ----")
    # A real line source is not a 0-ohm source, and VR6 loads it: the
    # master volume is 50k straight across the input, ahead of any
    # blocking cap.
    A(".param vamp=0.1 vfreq=1k rsrc=600")
    A("Vin SRC 0 DC 0 AC 1 SIN(0 {vamp} {vfreq})")
    A("Rsrc SRC INPUT_PRE {rsrc}")
    for out in ("HIGH", "MID", "LOW"):
        A("Rload_%s %s 0 {rload}" % (out, out))
    A("")
    A(".end")
    return "\n".join(L) + "\n"


MODELS = r"""* Device models for the P148 crossover simulation.
* Hand-written - this is the physics, not the topology.  Everything else
* in sim/ comes out of the netlist the board is built from.

* ---------------------------------------------------------------------
*  MC33079 section.  A behavioural macromodel, not a vendor one: the
*  parameters below are the datasheet's typical figures, and the point is
*  to get the things that actually matter for THIS circuit right -
*  open-loop gain and bandwidth (they set how well the integrators
*  integrate), slew rate and output clipping (they set what happens at
*  level), input bias current (it sets the DC offset the output blocking
*  caps have to deal with).
*
*    Aol   110 dB          GBW   16 MHz        SR   7 V/us
*    Ib    0.4 uA typ      Vos   0.5 mV typ    Rout 37 ohm
*
*  gm and C1 set GBW = gm/(2*pi*C1); gm*R1 sets Aol; the limit() on the
*  transconductor's output current sets the slew rate, SR = Ilim/C1.
* ---------------------------------------------------------------------
*  Written with B sources throughout.  `Gname n+ n- VALUE={...}` is
*  PSpice syntax that ngspice only honours in compatibility mode - without
*  it the transconductor contributes nothing, every op-amp output sits at
*  zero, and the AC sweep comes back numerically flat at 1e-16 in all
*  three bands.  That looks exactly like a broken CIRCUIT and is a broken
*  MODEL, so: B sources, which are native.
.subckt OPAMP inp inn out vcc vee
Rin  inp inn 100meg
Ibp  inp 0   400n
Ibn  inn 0   400n
* gm = 1 mA/V into R1 = 316 Meg  ->  Aol = 110 dB
* gm / (2*pi*C1) = 16 MHz GBW;  Ilim / C1 = 7 V/us slew
* Vos folded into the expression rather than a series source, so no node
* hangs off a single element.
Bgm  0 n1 I = max(min(1m*(V(inp) + 0.5m - V(inn)), 70u), -70u)
R1   n1 0 316meg
C1   n1 0 9.95p
* Output: unity buffer clamped to 90% of each live rail (about +/-13.5 V
* on +/-15, which is the datasheet swing), and - importantly for the
* power-up analysis - a clamp that DEGRADES CORRECTLY as the rails come
* up.  Written as V(vee)+1.5 / V(vcc)-1.5 it inverts at low supply: with
* both rails at 0 the window becomes [+1.5, -1.5] and min(max(x,1.5),-1.5)
* pins the output at -1.5 V, which put a 1.4 V spike on every output
* during the supply ramp and looked exactly like the muting failing.  It
* was the model.  Scaling by the rails cannot invert, because
* V(vee) <= 0 <= V(vcc) always.
Bo   n2 0 V = min(max(V(n1), 0.9*V(vee)), 0.9*V(vcc))
Rout n2 out 37
.ends OPAMP

* ---------------------------------------------------------------------
*  J111 N-JFET, as a set of datasheet CORNERS rather than one model.
*  The part is specified Vgs(off) = -3.0 to -10 V and Rds(on) <= 30 ohm,
*  and that spread is the whole question for a JFET mute: the gate sits at
*  a fixed -15 V when off, so a part at the -10 V end has far less margin
*  against signal peaks than one at -3 V.
*
*  Beta is chosen per corner to land Rds(on) on the 30 ohm limit:
*  for small Vds, gds = 2*Beta*|Vto|, so Beta = 1/(2*30*|Vto|).
*  Ciss ~ 12 pF and Crss ~ 5 pF from the datasheet.
* ---------------------------------------------------------------------
.model JFET_M3  NJF(Vto=-3  Beta=5.56m Lambda=1e-4 Rd=1 Rs=1 Cgs=7p Cgd=5p Is=1e-14)
.model JFET_M5  NJF(Vto=-5  Beta=3.33m Lambda=1e-4 Rd=1 Rs=1 Cgs=7p Cgd=5p Is=1e-14)
.model JFET_M10 NJF(Vto=-10 Beta=1.67m Lambda=1e-4 Rd=1 Rs=1 Cgs=7p Cgd=5p Is=1e-14)

.model D1N4148 D(Is=2.52n Rs=0.568 N=1.752 Cjo=4p M=0.4 tt=20n Bv=100 Ibv=0.1u)
.model DLED    D(Is=1e-20 N=1.6 Rs=5)
"""


def main():
    doc, pins = load()
    os.makedirs(OUT, exist_ok=True)
    with open(os.path.join(OUT, "crossover.net"), "w") as f:
        f.write(emit(doc, pins))
    with open(os.path.join(OUT, "models.lib"), "w") as f:
        f.write(MODELS)
    # One file per JFET corner, each defining the model the deck calls
    # `JFET`, so an analysis picks a corner with a single .include and
    # every other line of the netlist stays identical between corners.
    #
    # Two parts, because the choice between them is the whole question for
    # this mute.  Both are the same die family in the same SOT-23 with the
    # same pinout; they differ in how hard they are to turn OFF:
    #
    #   J111  Vgs(off) -3.0 .. -10.0 V   Rds(on) <= 30 ohm
    #   J112  Vgs(off) -1.0 ..  -5.0 V   Rds(on) <= 50 ohm
    #
    # Beta per corner is set to land Rds(on) on the datasheet LIMIT, which
    # is the pessimistic end for mute depth: for small Vds the channel
    # conductance is gds = 2*Beta*|Vto|, so Beta = 1/(2*Rds*|Vto|).
    for part, rds, corners in (("j111", 30.0, (-3.0, -5.0, -10.0)),
                               ("j112", 50.0, (-1.0, -3.0, -5.0))):
        for vto in corners:
            beta = 1.0 / (2.0 * rds * abs(vto))
            tag = "%s-m%g" % (part, abs(vto))
            with open(os.path.join(OUT, "jfet-%s.lib" % tag), "w") as f:
                f.write("* %s corner: Vgs(off) = %.1f V, Rds(on) = %.0f ohm\n"
                        ".model JFET NJF(Vto=%g Beta=%g Lambda=1e-4 Rd=1 "
                        "Rs=1 Cgs=7p Cgd=5p Is=1e-14)\n"
                        % (part.upper(), vto, rds, vto, beta))
    print("wrote sim/crossover.net (%d devices) and sim/models.lib"
          % sum(1 for r in pins if not r.startswith(("J", "TP"))))


if __name__ == "__main__":
    sys.exit(main())
